const fs = require("fs");
const path = require("path");

/**
 * The eval scorecard is generated by `npm run eval` and committed as
 * `evals/report.md`. It was only ever readable on GitHub, which meant the one
 * artefact that says whether generation quality is holding lived outside the
 * product. This reads that same committed file and returns it as data.
 *
 * Nothing here re-runs the harness: the report is an input, not a computation.
 * Running evals hits real providers and costs money, so it stays a deliberate
 * local/CI action and this endpoint only reports the result.
 */

const REPORT_PATH =
  process.env.EVALS_REPORT_PATH || path.resolve(__dirname, "..", "..", "evals", "report.md");
const PROMPTS_PATH =
  process.env.EVALS_PROMPTS_PATH || path.resolve(__dirname, "..", "..", "evals", "prompts.json");

/** Structural validity is a hard gate in runEvals.js; keep the two in sync. */
const STRUCTURE_GATE = 0.9;

/**
 * "100%" -> 1, "n/a" -> null.
 *
 * `null` and `0` mean different things on this scorecard -- "not measured" vs
 * "measured and failed" -- so the distinction has to survive parsing.
 */
function parseScore(cell) {
  if (typeof cell !== "string") return null;
  const trimmed = cell.trim();
  if (!trimmed || trimmed.toLowerCase() === "n/a") return null;
  const match = trimmed.match(/^(-?[\d.]+)\s*%$/);
  if (!match) return null;
  const value = Number(match[1]);
  return Number.isFinite(value) ? value / 100 : null;
}

function parseTableRow(line) {
  // "| json-basics | 100% | n/a | n/a |" -> ["json-basics", "100%", "n/a", "n/a"]
  return line
    .trim()
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

/**
 * Parses the markdown the harness writes. Kept pure and exported so the shape
 * contract between runEvals.js and this endpoint is unit-testable without
 * touching the filesystem.
 */
function parseReport(markdown) {
  const lines = String(markdown).split(/\r?\n/);

  let generatedAt = null;
  let modeLabel = null;
  const rows = [];
  let aggregate = { structure: null, coverage: null, faithfulness: null };
  let note = null;

  for (const line of lines) {
    const meta = line.match(/^_Generated:\s*(\S+)\s*·\s*mode:\s*(.+?)_\s*$/);
    if (meta) {
      const parsed = new Date(meta[1]);
      generatedAt = Number.isNaN(parsed.getTime()) ? null : parsed.toISOString();
      modeLabel = meta[2].trim();
      continue;
    }

    const agg = line.match(
      /\*\*Aggregate\*\*.*?structure\s+([^,]+),\s*coverage\s+([^,]+),\s*faithfulness\s+([^.]+)\./i
    );
    if (agg) {
      aggregate = {
        structure: parseScore(agg[1]),
        coverage: parseScore(agg[2]),
        faithfulness: parseScore(agg[3]),
      };
      continue;
    }

    if (line.startsWith(">")) {
      // Strip the leading marker and markdown emphasis; the UI renders plain text.
      const text = line.replace(/^>\s?/, "").replace(/\*\*/g, "").trim();
      if (text) note = note ? `${note} ${text}` : text;
      continue;
    }

    if (line.trim().startsWith("|")) {
      const cells = parseTableRow(line);
      if (cells.length < 4) continue;
      const [id] = cells;
      // Skip the header row and the |---|---| separator.
      if (/^-+$/.test(id) || id.toLowerCase() === "prompt") continue;
      rows.push({
        id,
        structure: parseScore(cells[1]),
        coverage: parseScore(cells[2]),
        faithfulness: parseScore(cells[3]),
      });
    }
  }

  const mode = modeLabel && /^mock/i.test(modeLabel) ? "mock" : "live";

  return { generatedAt, mode, modeLabel, rows, aggregate, note };
}

/** Golden prompts are what each row was actually asked; without them a row id is opaque. */
function readPrompts() {
  try {
    const parsed = JSON.parse(fs.readFileSync(PROMPTS_PATH, "utf8"));
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * GET /api/evals/report
 *
 * Read-only view of the committed eval scorecard. Public for the same reason
 * /api/ai/status is: it exposes no keys, no prompts from users, and no
 * generated content -- only the quality numbers already in the repo.
 */
function getEvalReport(req, res) {
  let raw;
  try {
    raw = fs.readFileSync(REPORT_PATH, "utf8");
  } catch (error) {
    // A deploy that ships only the backend directory has no evals/ alongside
    // it. That is a missing artefact, not a server fault, so the page can say
    // so precisely instead of rendering a generic error.
    return res.json({
      available: false,
      reason: error.code === "ENOENT" ? "not-found" : "unreadable",
      gates: { structure: STRUCTURE_GATE, faithfulness: null },
    });
  }

  try {
    const parsed = parseReport(raw);
    const prompts = readPrompts();
    const byId = new Map(prompts.map((p) => [p.id, p]));

    const failUnder = Number(process.env.FAIL_UNDER);

    return res.json({
      available: true,
      generatedAt: parsed.generatedAt,
      mode: parsed.mode,
      modeLabel: parsed.modeLabel,
      note: parsed.note,
      rows: parsed.rows.map((row) => {
        const prompt = byId.get(row.id);
        return {
          ...row,
          prompt: prompt ? prompt.prompt : null,
          expectedSubtopics: prompt ? prompt.expectedSubtopics || [] : [],
        };
      }),
      aggregate: parsed.aggregate,
      gates: {
        structure: STRUCTURE_GATE,
        faithfulness: Number.isFinite(failUnder) && failUnder > 0 ? failUnder : null,
      },
      raw,
    });
  } catch (error) {
    console.error("[Evals] failed to parse report:", error);
    return res.status(500).json({ error: "Could not read the eval report." });
  }
}

module.exports = { getEvalReport, parseReport, parseScore, REPORT_PATH };
